# Backup of migration 0002_usuario.py

# Generated by Django 5.2.7 on 2025-11-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
