# Generated by Django 5.2.7 on 2025-12-08 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_tech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorias',
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books_tech.categoria'),
        ),
    ]
