# Generated by Django 5.2.7 on 2026-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_tech', '0005_post_imagem_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilautor',
            name='redes_sociais',
            field=models.TextField(blank=True, help_text='Cole uma URL por linha (ex: Instagram, LinkedIn, GitHub).', null=True),
        ),
    ]
